"""initial migration

Revision ID: 0e25c709ce4b
Revises: 
Create Date: 2025-10-05 23:18:51.780215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e25c709ce4b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.UUID(), nullable=True))
        batch_op.drop_constraint(batch_op.f('roles_name_key'), type_='unique')

    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_user_tenant_role'), type_='unique')
        batch_op.create_unique_constraint('uq_user_role_tenant', ['user_id', 'role_id', 'tenant_id'])
        batch_op.drop_constraint(batch_op.f('user_roles_user_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('user_roles_role_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'roles', ['role_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('user_roles_role_id_fkey'), 'roles', ['role_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('user_roles_user_id_fkey'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_constraint('uq_user_role_tenant', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_user_tenant_role'), ['user_id', 'tenant_id'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('roles_name_key'), ['name'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('tenant_id')

    # ### end Alembic commands ###
