"""add uq_user_role_tenant constraint

Revision ID: 25f16e27d49f
Revises: 206f7b309be5
Create Date: 2025-09-28 18:11:18.489675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25f16e27d49f'
down_revision: Union[str, Sequence[str], None] = '206f7b309be5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_user_role_tenant', ['user_id', 'role_id', 'tenant_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_role_tenant', type_='unique')

    # ### end Alembic commands ###
