# FILE: ima_service/migrations/script.py.mako
"""update user table

Revision ID: 30e31a5e353d
Revises: a28d1b6430c4
Create Date: 2025-09-19 20:31:15.374039+00:00
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa  # noqa: F401

# revision identifiers, used by Alembic.
revision = '30e31a5e353d'
down_revision = 'a28d1b6430c4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('gender', sa.Enum('UNSPECIFIED', 'MALE', 'FEMALE', 'NON_BINARY', 'OTHER', name='usergender', native_enum=False), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gender')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
