"""update user model

Revision ID: 61175167017e
Revises: 11cc01fb17de
Create Date: 2025-10-17 19:29:51.422218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61175167017e'
down_revision: Union[str, Sequence[str], None] = '11cc01fb17de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_super_user',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_super_user',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
