"""updated base

Revision ID: 835b69f470bd
Revises: 7e9c5f92ea85
Create Date: 2025-10-10 21:02:44.967853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '835b69f470bd'
down_revision: Union[str, Sequence[str], None] = '7e9c5f92ea85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('label', sa.Integer(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_column('label')

    # ### end Alembic commands ###
