# FILE: ima_service/migrations/script.py.mako
"""add users table

Revision ID: a28d1b6430c4
Revises: f63ffa44fd71
Create Date: 2025-09-19 19:10:21.300838+00:00
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa  # noqa: F401

# revision identifiers, used by Alembic.
revision = 'a28d1b6430c4'
down_revision = 'f63ffa44fd71'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
