"""updated models

Revision ID: e9084e012e00
Revises: aa767f9faa01
Create Date: 2025-10-10 22:14:07.747549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9084e012e00'
down_revision: Union[str, Sequence[str], None] = 'aa767f9faa01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.UUID(), nullable=True))
        batch_op.drop_constraint(batch_op.f('permissions_name_key'), type_='unique')
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('role_permissions_role_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('role_permissions_permission_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'roles', ['role_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'permissions', ['permission_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column('parent_id', sa.UUID(), nullable=True))
        batch_op.alter_column('is_system',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('roles_name_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_roles_is_system'), ['is_system'], unique=False)
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'roles', ['parent_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenants_is_active'), ['is_active'], unique=False)
        batch_op.drop_constraint(batch_op.f('tenants_parent_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tenants', ['parent_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('user_roles_user_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('user_roles_role_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('user_roles_tenant_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'roles', ['role_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', name='gender_enum', native_enum=False), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('is_superuser', sa.Boolean(), server_default='false', nullable=False))
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_is_superuser'), ['is_superuser'], unique=False)
        batch_op.create_unique_constraint('uq_users_email_tenant', ['email', 'tenant_id'])
        batch_op.drop_constraint(batch_op.f('users_tenant_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('users_tenant_id_fkey'), 'tenants', ['tenant_id'], ['id'])
        batch_op.drop_constraint('uq_users_email_tenant', type_='unique')
        batch_op.drop_index(batch_op.f('ix_users_is_superuser'))
        batch_op.drop_index(batch_op.f('ix_users_is_active'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.drop_column('is_superuser')
        batch_op.drop_column('country')
        batch_op.drop_column('gender')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('user_roles_tenant_id_fkey'), 'tenants', ['tenant_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('user_roles_role_id_fkey'), 'roles', ['role_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('user_roles_user_id_fkey'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('tenants_parent_id_fkey'), 'tenants', ['parent_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_tenants_is_active'))

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_roles_is_system'))
        batch_op.create_unique_constraint(batch_op.f('roles_name_key'), ['name'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('is_system',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.drop_column('parent_id')
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('role_permissions_permission_id_fkey'), 'permissions', ['permission_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('role_permissions_role_id_fkey'), 'roles', ['role_id'], ['id'])

    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_unique_constraint(batch_op.f('permissions_name_key'), ['name'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('tenant_id')

    # ### end Alembic commands ###
