"""update user & role table

Revision ID: ebbc85396987
Revises: eb3b65fb7cc9
Create Date: 2025-10-16 00:56:11.984332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ebbc85396987'
down_revision: Union[str, Sequence[str], None] = 'eb3b65fb7cc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_tokens_correlation_id'), table_name='auth_tokens')
    op.drop_index(op.f('ix_auth_tokens_trace_id'), table_name='auth_tokens')
    op.drop_column('auth_tokens', 'ip_address')
    op.drop_column('auth_tokens', 'extra')
    op.drop_column('auth_tokens', 'session_type')
    op.drop_column('auth_tokens', 'mfa_verified')
    op.drop_column('auth_tokens', 'device_info')
    op.drop_column('auth_tokens', 'correlation_id')
    op.drop_column('auth_tokens', 'trace_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_tokens', sa.Column('trace_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('auth_tokens', sa.Column('correlation_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('auth_tokens', sa.Column('device_info', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('auth_tokens', sa.Column('mfa_verified', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('auth_tokens', sa.Column('session_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('auth_tokens', sa.Column('extra', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('auth_tokens', sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_auth_tokens_trace_id'), 'auth_tokens', ['trace_id'], unique=False)
    op.create_index(op.f('ix_auth_tokens_correlation_id'), 'auth_tokens', ['correlation_id'], unique=False)
    # ### end Alembic commands ###
