# FILE: ima_service/migrations/script.py.mako
"""another change

Revision ID: f63ffa44fd71
Revises: 93a61f081208
Create Date: 2025-09-19 18:54:20.799100+00:00
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa  # noqa: F401

# revision identifiers, used by Alembic.
revision = 'f63ffa44fd71'
down_revision = '93a61f081208'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
