"""create ingested_files table

Revision ID: 7283d5ee8579
Revises: 
Create Date: 2026-07-03 23:46:19.013873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7283d5ee8579'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingested_files',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('uploaded_by', sa.Uuid(), nullable=False),
    sa.Column('file_type', sa.Enum('BILL_PDF', 'BILL_IMAGE', 'NEM12_CSV', 'REC_CERTIFICATE', 'LGC_CERTIFICATE', 'PPA_CONTRACT', name='file_type'), nullable=False),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_bucket', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=1024), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'VALIDATING', 'VALIDATED', 'VALIDATION_FAILED', 'DISPATCHING', 'DISPATCHED', 'DISPATCH_FAILED', name='ingestion_status'), nullable=False),
    sa.Column('validation_errors', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('dispatched_to', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingested_files_status'), 'ingested_files', ['status'], unique=False)
    op.create_index(op.f('ix_ingested_files_tenant_id'), 'ingested_files', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingested_files_tenant_id'), table_name='ingested_files')
    op.drop_index(op.f('ix_ingested_files_status'), table_name='ingested_files')
    op.drop_table('ingested_files')
    # ### end Alembic commands ###
    # Postgres ENUM types are separate objects from the table/column that
    # used them — DROP TABLE leaves them orphaned, so a downgrade -> upgrade
    # cycle would otherwise fail with "type already exists".
    sa.Enum(name='file_type').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='ingestion_status').drop(op.get_bind(), checkfirst=True)
